<?php
/**
 * FormTableDefinitionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ocrapi
 *
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FormTableDefinitionTest Class Doc Comment
 *
 * @category    Class
 * @description Definition of a form table for OCR data extraction from images
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FormTableDefinitionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FormTableDefinition"
     */
    public function testFormTableDefinition()
    {
    }

    /**
     * Test attribute "table_id"
     */
    public function testPropertyTableId()
    {
    }

    /**
     * Test attribute "column_definitions"
     */
    public function testPropertyColumnDefinitions()
    {
    }

    /**
     * Test attribute "target_table_height_relative"
     */
    public function testPropertyTargetTableHeightRelative()
    {
    }

    /**
     * Test attribute "target_row_height_relative"
     */
    public function testPropertyTargetRowHeightRelative()
    {
    }
}
