<?php
/**
 * ImageOcrApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ocrapi
 *
 * The powerful Optical Character Recognition (OCR) APIs let you convert scanned images of pages into recognized text.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ImageOcrApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ImageOcrApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for imageOcrImageLinesWithLocation
     *
     * Convert a scanned image into words with location.
     *
     */
    public function testImageOcrImageLinesWithLocation()
    {
    }

    /**
     * Test case for imageOcrImageWordsWithLocation
     *
     * Convert a scanned image into words with location.
     *
     */
    public function testImageOcrImageWordsWithLocation()
    {
    }

    /**
     * Test case for imageOcrPhotoToText
     *
     * Convert a photo of a document into text.
     *
     */
    public function testImageOcrPhotoToText()
    {
    }

    /**
     * Test case for imageOcrPost
     *
     * Convert a scanned image into text.
     *
     */
    public function testImageOcrPost()
    {
    }
}
